name: C/C++ CI

on:
  push:
    branches:
      - master
      - actions-dev
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        epics_base: [R3.15.5, R3.15.8, R7.0.3.1, R7.0.4.1]
        asyn: [R4-32, R4-39, R4-41]

    steps:
    - name: EPICS base checkout
      uses: actions/checkout@v2
      with:
        repository: epics-base/epics-base
        ref: ${{ matrix.epics_base }}
        submodules: recursive
        path: base

    - name: List workspace with base
      run: ls ${{ github.workspace }}

    - name: make epics-base
      run: |
        cd base
        make

    - name: asyn checkout
      uses: actions/checkout@v2
      with:
        repository: epics-modules/asyn
        ref: ${{ matrix.asyn }}
        path: modules/asyn

    - name: Update asyn config file
      run: |
        cd modules/asyn/configure
        sed -i 's/EPICS_BASE=/#EPICS_BASE=/g' RELEASE
        sed -i "/EPICS_BASE=/a EPICS_BASE=$EPICS_BASE" RELEASE
        sed -i 's/IPAC=/#IPAC=/g' RELEASE
        sed -i 's/SNCSEQ=/#SNCSEQ=/g' RELEASE
        cat RELEASE
        cd ../../..
      env:
        EPICS_BASE: ${{ github.workspace }}/base

    - name: make asyn
      run: |
        cd modules/asyn
        make

    - name: ipmiComm checkout
      uses: actions/checkout@v2
      with:
        path: ipmiComm

    - name: List the workspace contents
      run: find ${{ github.workspace }} -maxdepth 2 -mindepth 2 -type d

    - name: make ipmiComm
      run: |
        cd ipmiComm
        sed -i 's/ASYN_MODULE_VERSION=/#ASYN_MODULE_VERSION=/g' configure/RELEASE.local
        make
      env:
        EPICS_SITE_TOP: ${{ github.workspace }}
        EPICS_MODULES: ${{ github.workspace }}/modules
