name: C/C++ CI

on:
  push:
    branches:
      - master
      - actions-dev
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_MODULE_VERSION: R7.0.3.1
      EPICS_MODULES: ${{ github.workspace }}
    steps:
    - name: EPICS base checkout
      uses: actions/checkout@v2
      with:
        repository: epics-base/epics-base
        ref: R7.0.3.1
        submodules: recursive
        path: base
    - name: view empty workspace
      run: ls ${{ github.workspace }}
    - name: make epics-base
      run: |
        cd base
        make
    - name: asyn checkout
      uses: actions/checkout@v2
      with:
        repository: epics-modules/asyn
        ref: R4-41
        path: asyn
    - name: update asyn config file
      run: |
        cd asyn/configure
        sed -i 's+/corvette/usr/local/epics-devel/base-7.0.4+/base' RELEASE
        cd ../..
    - name: make asyn
      run: |
        cd asyn
        make
      env:
        EPICS_SITE_TOP: base
    - name: ipmiComm checkout
      uses: actions/checkout@v2
      with:
        path: ipmiComm
    - name: view workspace
      run: ls ${{ github.workspace }}
    - name: make ipmiComm
      run: |
        cd ipmiComm
        make
      env:
        EPICS_SITE_TOP: base
