name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: EPICS base checkout
      uses: actions/checkout@v2
      with:
        repository: epics-base/epics-base
        ref: R7.0.3.1
        submodules: recursive
        path: epics-base
    - name: make epics-base
      run: |
        cd epics-base
        make
    - name: ipmiComm checkout
      uses: actions/checkout@v2
    - name: make ipmiComm
      run: make
